# Ex2: Matrices

## Câu 1:
- Viết function cal_matrices(op, m1, m2) với op là một trong các toán tử +, -, *, /; m1 và m2 là ma trận (numpy array). Hãy thực hiện việc tính toán theo toán tử và hai ma trận được truyền vào. Kết quả trả về là một ma trận/giá trị tương ứng.
- Gọi function này với các toán tử khác nhau để xem kết quả

## Câu 2:
- Cho ma trận A = [[1, 3, 3], [4, 5, 6], [7, 8, 9]] và ma trận B = [[2, 3], [6, 8], [5, 7]]
- Thực hiện dot product cho A.B bằng dot và @

## Câu 1: Gợi ý

In [12]:
import numpy as np

In [47]:
def cal_matrices(op, m1, m2):
    return eval(f"m1 {op} m2")

In [48]:
m1 = np.array([[1, 3, 2, 4], [4, 3, 6, 8], [5, 6, 3, 1]])
m2 = np.array([[2, 4, 5, 1], [5, 1, 2, 3], [1, 8, 1, 9]])

In [49]:

cal_matrices("+", m1, m2)

array([[ 3,  7,  7,  5],
       [ 9,  4,  8, 11],
       [ 6, 14,  4, 10]])

In [50]:
cal_matrices("-", m1, m2)

array([[-1, -1, -3,  3],
       [-1,  2,  4,  5],
       [ 4, -2,  2, -8]])

In [51]:
cal_matrices("*", m1, m2)

array([[ 2, 12, 10,  4],
       [20,  3, 12, 24],
       [ 5, 48,  3,  9]])

In [52]:
cal_matrices("/", m1, m2)

array([[0.5       , 0.75      , 0.4       , 4.        ],
       [0.8       , 3.        , 3.        , 2.66666667],
       [5.        , 0.75      , 3.        , 0.11111111]])

## Câu 2: Gợi ý
- Cho ma trận A = [[1, 3, 3], [4, 5, 6], [7, 8, 9]] và ma trận B = [[2, 3], [6, 8], [5, 7]]
- Thực hiện dot product cho A.B bằng dot và @

In [44]:
A = np.matrix([[1, 3, 3], [4, 5, 6], [7, 8, 9]])
B = np.matrix( [[2, 3], [6, 8], [5, 7]])

In [45]:
A_dot_B = A.dot(B)
A_dot_B

matrix([[ 35,  48],
        [ 68,  94],
        [107, 148]])

In [46]:
A_B = A@B
A_B

matrix([[ 35,  48],
        [ 68,  94],
        [107, 148]])