# Ex1: Decomposition

## Câu 1: LU Decomposition
- Tạo ma trận A(4x4) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
- Phân tích thành các thành phần P, L, U. In kết quả
- Tại tạo ma trận B từ các thành phần P, L, U. 

## Câu 2: Hãy dùng LU Decompostion để làm lại bài toán này:
- Cho: <br/>
    2a + b  + c = 4<br/> 
     a + 3b + 2c = 5<br/>
     a          = 6<br/>   
- Quy về Ax = B. Sau đó giải tìm x
- Phân tích thành các thành phần P, L, U từ A. In kết quả
- Tại tạo ma trận A từ các thành phần P, L, U với tên là A_new

## Câu 3: QR Decomposition
- Tạo ma trận C(4x5) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
- Phân tích thành các thành phần Q, R. In kết quả
- Tái tạo ma trận D từ các thành phần Q, R. 

## Câu 4: Cholesky Decomposition
- Tạo ma trận E(3x3) vuông chứa các giá trị ngẫu nhiên trong khoảng 3 - 9.
- Từ đó chuyển E thành ma trận vuông đối xứng theo tam giác dưới dường chéo chính
- Kiểm tra nếu mọi thành phần đều không âm thì:
    - Phân tích thành L. In kết quả
    - Tái tạo ma trận F từ các thành phần L.L.T 
- Ngược lại thì thông báo E có thành phần âm
- Chú ý: dùng np.linalg.eigvalsh(E) để kiểm tra xem mọi thành phần có âm hay không
- Mở rộng: Thực hiện việc tạo ma trận vuông đối xứng với mọi thành phần đều không âm và phân tích.

## Câu 1: LU Decomposition (Gợi ý)

In [1]:
from lib import *
import numpy
import scipy
from scipy.linalg import lu

In [2]:
A = create_matrix_random(4, 4, 1, 10)
A

array([[ 3.,  2.,  5.,  9.],
       [ 1.,  7.,  5.,  7.],
       [ 5., 10.,  5.,  3.],
       [ 6.,  9.,  7.,  2.]])

In [3]:
P, L, U = lu(A)

In [4]:
P

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [5]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.16666667,  1.        ,  0.        ,  0.        ],
       [ 0.5       , -0.45454545,  1.        ,  0.        ],
       [ 0.83333333,  0.45454545, -0.79439252,  1.        ]])

In [6]:
U

array([[ 6.        ,  9.        ,  7.        ,  2.        ],
       [ 0.        ,  5.5       ,  3.83333333,  6.66666667],
       [ 0.        ,  0.        ,  3.24242424, 11.03030303],
       [ 0.        ,  0.        ,  0.        ,  7.06542056]])

In [7]:
B = P.dot(L).dot(U)
B

array([[ 3.,  2.,  5.,  9.],
       [ 1.,  7.,  5.,  7.],
       [ 5., 10.,  5.,  3.],
       [ 6.,  9.,  7.,  2.]])

## Câu 2: Hãy dùng LU Decompostion để làm lại bài toán này:
- Cho: <br/>
    2a + b  + c = 4<br/> 
     a + 3b + 2c = 5<br/>
     a          = 6<br/>   
- Quy về Ax = B. Sau đó giải tìm x
- Phân tích thành các thành phần P, L, U từ A. In kết quả
- Tại tạo ma trận A từ các thành phần P, L, U với tên là A_new

In [8]:
import scipy.linalg as linalg 

In [9]:
# define matrix A using Numpy arrays 
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]]) 

In [10]:
# define matrix B 
B = np.array([4, 5, 6]) 

In [11]:
# With LU = A
LU = linalg.lu_factor(A) 

In [12]:
#solve given LU and B 
x = linalg.lu_solve(LU, B) 
print("Solutions(a, b, c):\n",x) 

Solutions(a, b, c):
 [  6.  15. -23.]


In [13]:
P, L, U = scipy.linalg.lu(A) 

In [14]:
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0.5, -0.2,  1. ]])

In [16]:
U

array([[ 2. ,  1. ,  1. ],
       [ 0. ,  2.5,  1.5],
       [ 0. ,  0. , -0.2]])

In [17]:
A_new = P.dot(L).dot(U)
A_new

array([[ 2.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  3.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00, -2.77555756e-17,  2.77555756e-17]])

## Câu 3: QR Decomposition (Gợi ý)
- Tạo ma trận C(4x5) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
- Phân tích thành các thành phần Q, R. In kết quả
- Tái tạo ma trận D từ các thành phần Q, R. 

In [18]:
from numpy.linalg import qr

In [19]:
B = create_matrix_random(4, 5, 5, 10)
B

array([[ 6.,  6.,  7.,  9.,  8.],
       [ 7., 10.,  5., 11.,  5.],
       [ 8., 11.,  6., 10.,  6.],
       [ 7., 11.,  7.,  5.,  8.]])

In [20]:
Q, R = qr(B, 'complete')

In [21]:
Q

array([[-0.42640143,  0.8310223 ,  0.34330136, -0.09863023],
       [-0.49746834, -0.15747683, -0.44566639, -0.72739794],
       [-0.56853524, -0.01897311, -0.46541527,  0.67808283],
       [-0.49746834, -0.53314445,  0.68331125,  0.03698634]])

In [22]:
R

array([[-14.07124728, -19.25913138, -12.36564155, -17.48245874,
        -13.28951132],
       [  0.        ,  -2.66192761,   1.18392219,   2.89150226,
          1.48180004],
       [  0.        ,   0.        ,   2.1654647 ,  -3.05021452,
          3.19207731],
       [  0.        ,   0.        ,   0.        ,  -1.92328948,
         -0.06164389]])

In [23]:
C = Q.dot(R)

In [24]:
C

array([[ 6.,  6.,  7.,  9.,  8.],
       [ 7., 10.,  5., 11.,  5.],
       [ 8., 11.,  6., 10.,  6.],
       [ 7., 11.,  7.,  5.,  8.]])

## Câu 4: Cholesky Decomposition (Gợi ý)
- Tạo ma trận E(3x3) vuông chứa các giá trị ngẫu nhiên trong khoảng 3 - 9.
- Từ đó chuyển E thành ma trận vuông đối xứng theo tam giác dưới dường chéo chính
- Kiểm tra nếu mọi thành phần đều không âm thì:
    - Phân tích thành L. In kết quả
    - Tái tạo ma trận F từ các thành phần L.L.T 
- Ngược lại thì thông báo E có thành phần âm
- Chú ý: dùng np.linalg.eigvalsh(E) để kiểm tra xem mọi thành phần có âm hay không
- Mở rộng: Thực hiện việc tạo ma trận vuông đối xứng với mọi thành phần đều không âm và phân tích.

In [25]:
from numpy.linalg import cholesky

In [26]:
E = create_matrix_random(3, 3, 3, 9)
E

array([[6., 8., 5.],
       [3., 8., 5.],
       [4., 9., 3.]])

In [27]:
E.shape

(3, 3)

In [28]:
for i in range(E.shape[0]):
    for j in range(i):
        E[j][i] = E[i][j]
E

array([[6., 3., 4.],
       [3., 8., 9.],
       [4., 9., 3.]])

In [29]:
# Chú ý: Có 1 thành phần bị âm nên sẽ không tạo được L.
# Kiểm tra mọi thành phần đều dương thì tạo L

In [30]:
test = np.linalg.eigvalsh(E)
test

array([-4.05308411,  4.08618749, 16.96689662])

In [31]:
flag = np.all(test>0)

In [32]:
if flag==True:
    L = cholesky(E)
    print(L)
    F = L.dot(L.T)
else:
    print('E not positive definite')

E not positive definite


In [33]:
def create_matrix_positive_definite(m, n, start, end):
    E = None
    flag = False
    while flag == False:
        E =  create_matrix_random(m, n, start, end)
        for i in range(E.shape[0]):
            for j in range(i):
                E[j][i] = E[i][j]
        test = np.linalg.eigvalsh(E)
        flag = np.all(test>0)
    return E

In [34]:
E = create_matrix_positive_definite(3, 3, 3, 9)
E

array([[8., 5., 6.],
       [5., 8., 3.],
       [6., 3., 6.]])

In [35]:
L = cholesky(E)
print(L)

[[ 2.82842712  0.          0.        ]
 [ 1.76776695  2.20794022  0.        ]
 [ 2.12132034 -0.33968311  1.17669681]]


In [36]:
F = L.dot(L.T)
print(F)

[[8. 5. 6.]
 [5. 8. 3.]
 [6. 3. 6.]]
